language: node_js
node_js:
  - node
notifications:
  slack:
    secure: GUW4+P0YUXzElP+/X3i5ggCVJiDaO/pnoz1LLh7dD7daauo+HBlwm5X9mC8cseN8JOD/qNhTfoVcn3uV8vUoYvZhKYLYIiu5nwrJghGloJu6gIDCJlwELtcNvrX6k0VCLfZq/dIVFe48WkZzKh5evExNB5/v4WphImAEsAMMk6BhGp5f7UZhJ3IsZpUHroqYzT+e1kzLbvCCIUV0FzfLuiGYI7M0EKiiiE18ilyVmD1vIHHinHQlxEI8BBz258vD8wm0Ci7zYW7uRau1TvacURXeSuZ7vUMstXYD2wJokWweSvH82QQRuO+lV6tVqTzCPaUE9qXGkIDGh6WY+H3xt0PKftnPHiqL+B5rediH6W6wURqndGMoyW8ZjpMR/HbIzITxWhdW7noifU0GFg/hzRGEnltQhBTUdDOuU5kpktFHWZRfs4HrPXAEPMkgVQ5q/cnLRNlpaPROVcAZ+mb+5kQyikSjjNgxijFXwvBdP3ujkqlK4LIWtJeEGKs17qR/U4qnWIl6TqMgxfxAsYvlEl92O33u2pHq3YPlcwrE8AwgmeDH9zwGNvQiM4TNk3Pc/hZF7+ewH2sSqJZLSNMeECfw/5qql6OGKSwaR+zhmYIIfFprxNqkuAYFci3IZwlRybknYM3a/05KfT6zGLH/Iw31oO32wYsDYbMqnC+lPj8=
